insert into car (name, maker, year) values ('Ranger', 'Ford', 1996);
insert into car (name, maker, year) values ('Savana 3500', 'GMC', 2003);
insert into car (name, maker, year) values ('300SL', 'Mercedes-Benz', 1993);
insert into car (name, maker, year) values ('Astro', 'Chevrolet', 1998);
insert into car (name, maker, year) values ('A8', 'Audi', 2012);
insert into car (name, maker, year) values ('Q', 'Infiniti', 2002);
insert into car (name, maker, year) values ('62', 'Maybach', 2004);
insert into car (name, maker, year) values ('MX-6', 'Mazda', 1992);
insert into car (name, maker, year) values ('Sierra 2500', 'GMC', 2008);
insert into car (name, maker, year) values ('Discovery', 'Land Rover', 1995);
insert into car (name, maker, year) values ('Silhouette', 'Oldsmobile', 1992);
insert into car (name, maker, year) values ('F-Series', 'Ford', 2003);
insert into car (name, maker, year) values ('Alcyone SVX', 'Subaru', 1993);
insert into car (name, maker, year) values ('Beetle', 'Volkswagen', 1965);
insert into car (name, maker, year) values ('Miata MX-5', 'Mazda', 2008);
insert into car (name, maker, year) values ('Expedition EL', 'Ford', 2007);
insert into car (name, maker, year) values ('F350', 'Ford', 2009);
insert into car (name, maker, year) values ('xD', 'Scion', 2012);
insert into car (name, maker, year) values ('Mazda3', 'Mazda', 2007);
insert into car (name, maker, year) values ('STS-V', 'Cadillac', 2008);
insert into car (name, maker, year) values ('TrailBlazer', 'Chevrolet', 2004);
insert into car (name, maker, year) values ('Rio', 'Kia', 2012);
insert into car (name, maker, year) values ('G', 'Infiniti', 1994);
insert into car (name, maker, year) values ('928', 'Porsche', 1988);
insert into car (name, maker, year) values ('Murciélago', 'Lamborghini', 2010);
insert into car (name, maker, year) values ('Ion', 'Saturn', 2007);
insert into car (name, maker, year) values ('TrailBlazer', 'Chevrolet', 2004);
insert into car (name, maker, year) values ('S-Type', 'Jaguar', 2001);
insert into car (name, maker, year) values ('Diablo', 'Lamborghini', 2000);
insert into car (name, maker, year) values ('Accord', 'Honda', 1983);
insert into car (name, maker, year) values ('Elantra', 'Hyundai', 1994);
insert into car (name, maker, year) values ('S4', 'Audi', 1993);
insert into car (name, maker, year) values ('Metro', 'Geo', 1993);
insert into car (name, maker, year) values ('W201', 'Mercedes-Benz', 1985);
insert into car (name, maker, year) values ('F450', 'Ford', 2009);
insert into car (name, maker, year) values ('Lumina', 'Chevrolet', 2000);
insert into car (name, maker, year) values ('QX', 'Infiniti', 2005);
insert into car (name, maker, year) values ('7 Series', 'BMW', 1998);
insert into car (name, maker, year) values ('Touareg', 'Volkswagen', 2010);
insert into car (name, maker, year) values ('Mark VIII', 'Lincoln', 1994);
insert into car (name, maker, year) values ('Silverado 3500', 'Chevrolet', 2008);
insert into car (name, maker, year) values ('ES', 'Lexus', 1995);
insert into car (name, maker, year) values ('Murciélago', 'Lamborghini', 2003);
insert into car (name, maker, year) values ('Caravan', 'Dodge', 1999);
insert into car (name, maker, year) values ('E-Class', 'Mercedes-Benz', 1993);
insert into car (name, maker, year) values ('B-Series Plus', 'Mazda', 2002);
insert into car (name, maker, year) values ('F450', 'Ford', 2012);
insert into car (name, maker, year) values ('Savana', 'GMC', 2006);
insert into car (name, maker, year) values ('9000', 'Saab', 1991);
insert into car (name, maker, year) values ('Cayenne', 'Porsche', 2008);
insert into car (name, maker, year) values ('Elantra', 'Hyundai', 1999);
insert into car (name, maker, year) values ('Passat', 'Volkswagen', 1999);
insert into car (name, maker, year) values ('Galant', 'Mitsubishi', 2007);
insert into car (name, maker, year) values ('Villager', 'Mercury', 1998);
insert into car (name, maker, year) values ('Pajero', 'Mitsubishi', 1987);
insert into car (name, maker, year) values ('Hombre Space', 'Isuzu', 1999);
insert into car (name, maker, year) values ('S4', 'Audi', 2007);
insert into car (name, maker, year) values ('GTI', 'Volkswagen', 2000);
insert into car (name, maker, year) values ('Cube', 'Nissan', 2010);
insert into car (name, maker, year) values ('5 Series', 'BMW', 1999);
insert into car (name, maker, year) values ('Protege5', 'Mazda', 2002);
insert into car (name, maker, year) values ('RAV4', 'Toyota', 2007);
insert into car (name, maker, year) values ('Voyager', 'Plymouth', 1998);
insert into car (name, maker, year) values ('300SE', 'Mercedes-Benz', 1993);
insert into car (name, maker, year) values ('Tacoma', 'Toyota', 1999);
insert into car (name, maker, year) values ('S-Class', 'Mercedes-Benz', 2004);
insert into car (name, maker, year) values ('Cordia', 'Mitsubishi', 1985);
insert into car (name, maker, year) values ('LeMans', 'Pontiac', 1965);
insert into car (name, maker, year) values ('ES', 'Lexus', 2006);
insert into car (name, maker, year) values ('Eclipse', 'Mitsubishi', 1997);
insert into car (name, maker, year) values ('Hombre', 'Isuzu', 1997);
insert into car (name, maker, year) values ('xA', 'Scion', 2004);
insert into car (name, maker, year) values ('Skylark', 'Buick', 1985);
insert into car (name, maker, year) values ('Eurovan', 'Volkswagen', 1999);
insert into car (name, maker, year) values ('430 Scuderia', 'Ferrari', 2009);
insert into car (name, maker, year) values ('Sequoia', 'Toyota', 2009);
insert into car (name, maker, year) values ('Envoy XL', 'GMC', 2004);
insert into car (name, maker, year) values ('Savana 3500', 'GMC', 2010);
insert into car (name, maker, year) values ('GS', 'Lexus', 2005);
insert into car (name, maker, year) values ('Dakota Club', 'Dodge', 1997);
insert into car (name, maker, year) values ('Continental Flying Spur', 'Bentley', 2010);
insert into car (name, maker, year) values ('Express 1500', 'Chevrolet', 2010);
insert into car (name, maker, year) values ('Outlander', 'Mitsubishi', 2005);
insert into car (name, maker, year) values ('XC70', 'Volvo', 2006);
insert into car (name, maker, year) values ('Monte Carlo', 'Chevrolet', 2006);
insert into car (name, maker, year) values ('X5', 'BMW', 2004);
insert into car (name, maker, year) values ('XJ', 'Jaguar', 2011);
insert into car (name, maker, year) values ('NSX', 'Acura', 1994);
insert into car (name, maker, year) values ('LR2', 'Land Rover', 2010);
insert into car (name, maker, year) values ('Corolla', 'Toyota', 2002);
insert into car (name, maker, year) values ('Yukon', 'GMC', 2004);
insert into car (name, maker, year) values ('Bravada', 'Oldsmobile', 1997);
insert into car (name, maker, year) values ('9000', 'Saab', 1996);
insert into car (name, maker, year) values ('S-Class', 'Mercedes-Benz', 1985);
insert into car (name, maker, year) values ('Solara', 'Toyota', 2004);
insert into car (name, maker, year) values ('Comanche', 'Jeep', 1992);
insert into car (name, maker, year) values ('F-Series', 'Ford', 1997);
insert into car (name, maker, year) values ('Econoline E250', 'Ford', 2001);
insert into car (name, maker, year) values ('Challenger', 'Mitsubishi', 2004);
insert into car (name, maker, year) values ('Range Rover', 'Land Rover', 1996);
insert into car (name, maker, year) values ('Carens', 'Kia', 2007);
insert into car (name, maker, year) values ('Journey', 'Dodge', 2012);
insert into car (name, maker, year) values ('Econoline E150', 'Ford', 2001);
insert into car (name, maker, year) values ('EX', 'Infiniti', 2010);
insert into car (name, maker, year) values ('Cougar', 'Mercury', 1994);
insert into car (name, maker, year) values ('S60', 'Volvo', 2013);
insert into car (name, maker, year) values ('5000S', 'Audi', 1984);
insert into car (name, maker, year) values ('SJ', 'Suzuki', 1991);
insert into car (name, maker, year) values ('Talon', 'Eagle', 1990);
insert into car (name, maker, year) values ('EXP', 'Ford', 1987);
insert into car (name, maker, year) values ('Suburban 2500', 'Chevrolet', 2000);
insert into car (name, maker, year) values ('Avalanche 1500', 'Chevrolet', 2004);
insert into car (name, maker, year) values ('Outlander', 'Mitsubishi', 2009);
insert into car (name, maker, year) values ('Sienna', 'Toyota', 1998);
insert into car (name, maker, year) values ('Solara', 'Toyota', 1999);
insert into car (name, maker, year) values ('Wrangler', 'Jeep', 2011);
insert into car (name, maker, year) values ('RX-8', 'Mazda', 2011);
insert into car (name, maker, year) values ('Catera', 'Cadillac', 2001);
insert into car (name, maker, year) values ('Taurus', 'Ford', 2006);
insert into car (name, maker, year) values ('B-Series', 'Mazda', 2002);
insert into car (name, maker, year) values ('Eclipse', 'Mitsubishi', 1989);
insert into car (name, maker, year) values ('T100 Xtra', 'Toyota', 1997);
insert into car (name, maker, year) values ('Cobalt', 'Chevrolet', 2005);
insert into car (name, maker, year) values ('Thunderbird', 'Ford', 1990);
insert into car (name, maker, year) values ('9-2X', 'Saab', 2005);
insert into car (name, maker, year) values ('500E', 'Mercedes-Benz', 1992);
insert into car (name, maker, year) values ('Lumina', 'Chevrolet', 1994);
insert into car (name, maker, year) values ('Space', 'Isuzu', 1994);
insert into car (name, maker, year) values ('R-Class', 'Mercedes-Benz', 2007);
insert into car (name, maker, year) values ('Silhouette', 'Oldsmobile', 1997);
insert into car (name, maker, year) values ('Metro', 'Geo', 1994);
insert into car (name, maker, year) values ('Ranger', 'Ford', 1990);
insert into car (name, maker, year) values ('EX', 'Infiniti', 2010);
insert into car (name, maker, year) values ('S-Class', 'Mercedes-Benz', 1988);
insert into car (name, maker, year) values ('Challenger', 'Dodge', 2009);
insert into car (name, maker, year) values ('Accord', 'Honda', 1987);
insert into car (name, maker, year) values ('Highlander', 'Toyota', 2006);
insert into car (name, maker, year) values ('IS', 'Lexus', 2002);
insert into car (name, maker, year) values ('Elantra', 'Hyundai', 1998);
insert into car (name, maker, year) values ('Corrado', 'Volkswagen', 1991);
insert into car (name, maker, year) values ('Focus', 'Ford', 2006);
insert into car (name, maker, year) values ('SL-Class', 'Mercedes-Benz', 1985);
insert into car (name, maker, year) values ('Yukon', 'GMC', 2001);
insert into car (name, maker, year) values ('E-Series', 'Ford', 1989);
insert into car (name, maker, year) values ('Montero', 'Mitsubishi', 2004);
insert into car (name, maker, year) values ('3500', 'Ram', 2011);
insert into car (name, maker, year) values ('Grand Prix', 'Pontiac', 1989);
insert into car (name, maker, year) values ('Tacoma Xtra', 'Toyota', 1999);
insert into car (name, maker, year) values ('7 Series', 'BMW', 2009);
insert into car (name, maker, year) values ('Gemini', 'Pontiac', 1986);
insert into car (name, maker, year) values ('Daewoo Magnus', 'Suzuki', 2004);
insert into car (name, maker, year) values ('Ram 2500', 'Dodge', 2010);
insert into car (name, maker, year) values ('Cabriolet', 'Audi', 1997);
insert into car (name, maker, year) values ('Avalanche 2500', 'Chevrolet', 2006);
insert into car (name, maker, year) values ('Tribute', 'Mazda', 2001);
insert into car (name, maker, year) values ('H2 SUV', 'Hummer', 2006);
insert into car (name, maker, year) values ('Cavalier', 'Chevrolet', 1998);
insert into car (name, maker, year) values ('Elantra', 'Hyundai', 2008);
insert into car (name, maker, year) values ('S5', 'Audi', 2009);
insert into car (name, maker, year) values ('SL-Class', 'Mercedes-Benz', 1994);
insert into car (name, maker, year) values ('B-Series', 'Mazda', 1990);
insert into car (name, maker, year) values ('Celica', 'Toyota', 1997);
insert into car (name, maker, year) values ('CLK-Class', 'Mercedes-Benz', 2008);
insert into car (name, maker, year) values ('Grand Caravan', 'Dodge', 2006);
insert into car (name, maker, year) values ('Ranger', 'Ford', 2002);
insert into car (name, maker, year) values ('Grand Caravan', 'Dodge', 1992);
insert into car (name, maker, year) values ('300SD', 'Mercedes-Benz', 1992);
insert into car (name, maker, year) values ('7 Series', 'BMW', 1995);
insert into car (name, maker, year) values ('Sigma', 'Mitsubishi', 1990);
insert into car (name, maker, year) values ('ES', 'Lexus', 2007);
insert into car (name, maker, year) values ('M5', 'BMW', 2006);
insert into car (name, maker, year) values ('Sedona', 'Kia', 2011);
insert into car (name, maker, year) values ('Galant', 'Mitsubishi', 1991);
insert into car (name, maker, year) values ('GS', 'Lexus', 2006);
insert into car (name, maker, year) values ('Club Wagon', 'Ford', 1994);
insert into car (name, maker, year) values ('MX-6', 'Mazda', 1990);
insert into car (name, maker, year) values ('XJ Series', 'Jaguar', 1996);
insert into car (name, maker, year) values ('Bronco II', 'Ford', 1984);
insert into car (name, maker, year) values ('164', 'Alfa Romeo', 1994);
insert into car (name, maker, year) values ('Protege5', 'Mazda', 2003);
insert into car (name, maker, year) values ('CTS', 'Cadillac', 2007);
insert into car (name, maker, year) values ('Continental GTC', 'Bentley', 2010);
insert into car (name, maker, year) values ('Silverado 3500', 'Chevrolet', 2012);
insert into car (name, maker, year) values ('XJ Series', 'Jaguar', 1997);
insert into car (name, maker, year) values ('Sportage', 'Kia', 2008);
insert into car (name, maker, year) values ('Esprit', 'Lotus', 1989);
insert into car (name, maker, year) values ('S10', 'Chevrolet', 1994);
insert into car (name, maker, year) values ('Reatta', 'Buick', 1991);
insert into car (name, maker, year) values ('Cougar', 'Mercury', 1986);
insert into car (name, maker, year) values ('Crown Victoria', 'Ford', 1992);
insert into car (name, maker, year) values ('Sierra', 'GMC', 2008);
insert into car (name, maker, year) values ('Cube', 'Nissan', 2010);
insert into car (name, maker, year) values ('Reno', 'Suzuki', 2008);
insert into car (name, maker, year) values ('Escort', 'Ford', 1993);
insert into car (name, maker, year) values ('E-Class', 'Mercedes-Benz', 1999);
insert into car (name, maker, year) values ('xD', 'Scion', 2011);
insert into car (name, maker, year) values ('Scirocco', 'Volkswagen', 1984);
insert into car (name, maker, year) values ('Pilot', 'Honda', 2003);
insert into car (name, maker, year) values ('599 GTB Fiorano', 'Ferrari', 2010);
insert into car (name, maker, year) values ('Silverado 2500', 'Chevrolet', 2004);
insert into car (name, maker, year) values ('2500', 'GMC', 1995);
insert into car (name, maker, year) values ('Q5', 'Audi', 2009);
insert into car (name, maker, year) values ('Probe', 'Ford', 1989);
insert into car (name, maker, year) values ('Town & Country', 'Chrysler', 1996);
insert into car (name, maker, year) values ('Mountaineer', 'Mercury', 2009);
insert into car (name, maker, year) values ('Terrain', 'GMC', 2012);
insert into car (name, maker, year) values ('Mazda3', 'Mazda', 2008);
insert into car (name, maker, year) values ('1500 Club Coupe', 'GMC', 1992);
insert into car (name, maker, year) values ('Xterra', 'Nissan', 2009);
insert into car (name, maker, year) values ('Familia', 'Mazda', 1987);
insert into car (name, maker, year) values ('Ram Van B250', 'Dodge', 1992);
insert into car (name, maker, year) values ('X5 M', 'BMW', 2010);
insert into car (name, maker, year) values ('Prowler', 'Plymouth', 2000);
insert into car (name, maker, year) values ('Veloster', 'Hyundai', 2012);
insert into car (name, maker, year) values ('TT', 'Audi', 2000);
insert into car (name, maker, year) values ('RX-7', 'Mazda', 1983);
insert into car (name, maker, year) values ('Grand Am', 'Pontiac', 1986);
insert into car (name, maker, year) values ('EXP', 'Ford', 1985);
insert into car (name, maker, year) values ('GTI', 'Volkswagen', 2001);
insert into car (name, maker, year) values ('Safari', 'GMC', 2003);
insert into car (name, maker, year) values ('2CV', 'Citroën', 1948);
insert into car (name, maker, year) values ('Passat', 'Volkswagen', 1999);
insert into car (name, maker, year) values ('Integra', 'Acura', 1993);
insert into car (name, maker, year) values ('Blazer', 'Chevrolet', 1994);
insert into car (name, maker, year) values ('Cougar', 'Mercury', 1992);
insert into car (name, maker, year) values ('LS', 'Lexus', 2007);
insert into car (name, maker, year) values ('Yaris', 'Toyota', 2011);
insert into car (name, maker, year) values ('F250', 'Ford', 1984);
insert into car (name, maker, year) values ('Explorer Sport Trac', 'Ford', 2000);
insert into car (name, maker, year) values ('G35', 'Infiniti', 2004);
insert into car (name, maker, year) values ('9-5', 'Saab', 2007);
insert into car (name, maker, year) values ('VS Commodore', 'Holden', 1996);
insert into car (name, maker, year) values ('Cutlass Cruiser', 'Oldsmobile', 1993);
insert into car (name, maker, year) values ('Sierra 1500', 'GMC', 2011);
insert into car (name, maker, year) values ('FJ Cruiser', 'Toyota', 2012);
insert into car (name, maker, year) values ('XJ', 'Jaguar', 2008);
insert into car (name, maker, year) values ('E-Class', 'Mercedes-Benz', 1989);
insert into car (name, maker, year) values ('Sorento', 'Kia', 2007);
insert into car (name, maker, year) values ('626', 'Mazda', 1998);
insert into car (name, maker, year) values ('911', 'Porsche', 1998);
insert into car (name, maker, year) values ('Monte Carlo', 'Chevrolet', 1999);
insert into car (name, maker, year) values ('Continental', 'Lincoln', 1997);
insert into car (name, maker, year) values ('Sierra 2500', 'GMC', 2001);
insert into car (name, maker, year) values ('Miata MX-5', 'Mazda', 1994);
insert into car (name, maker, year) values ('H1', 'Hummer', 1994);
insert into car (name, maker, year) values ('Viper', 'Dodge', 2005);
insert into car (name, maker, year) values ('Corvette', 'Chevrolet', 2012);
insert into car (name, maker, year) values ('Familia', 'Mazda', 1990);
insert into car (name, maker, year) values ('Silverado 1500', 'Chevrolet', 2011);
insert into car (name, maker, year) values ('M3', 'BMW', 2003);
insert into car (name, maker, year) values ('Golf', 'Volkswagen', 2001);
insert into car (name, maker, year) values ('Capri', 'Mercury', 1985);
insert into car (name, maker, year) values ('GTI', 'Volkswagen', 2003);
insert into car (name, maker, year) values ('Prelude', 'Honda', 1986);
insert into car (name, maker, year) values ('SM', 'Citroën', 1972);
insert into car (name, maker, year) values ('GX', 'Lexus', 2003);
insert into car (name, maker, year) values ('3000GT', 'Mitsubishi', 1996);
insert into car (name, maker, year) values ('Cabriolet', 'Volkswagen', 1997);
insert into car (name, maker, year) values ('F350', 'Ford', 2008);
insert into car (name, maker, year) values ('Neon', 'Dodge', 2005);
insert into car (name, maker, year) values ('Malibu', 'Chevrolet', 1997);
insert into car (name, maker, year) values ('SL-Class', 'Mercedes-Benz', 1994);
insert into car (name, maker, year) values ('GTO', 'Pontiac', 1973);
insert into car (name, maker, year) values ('Discovery Series II', 'Land Rover', 1999);
insert into car (name, maker, year) values ('Lumina', 'Chevrolet', 1999);
insert into car (name, maker, year) values ('Golf', 'Volkswagen', 1998);
insert into car (name, maker, year) values ('Seville', 'Cadillac', 1998);
insert into car (name, maker, year) values ('Sonata', 'Hyundai', 2013);
insert into car (name, maker, year) values ('S-Class', 'Mercedes-Benz', 2007);
insert into car (name, maker, year) values ('Regency', 'Oldsmobile', 1998);
insert into car (name, maker, year) values ('Scoupe', 'Hyundai', 1992);
insert into car (name, maker, year) values ('4000CS Quattro', 'Audi', 1986);
insert into car (name, maker, year) values ('Frontier', 'Nissan', 2011);
insert into car (name, maker, year) values ('Dakota Club', 'Dodge', 1994);
insert into car (name, maker, year) values ('Azera', 'Hyundai', 2011);
insert into car (name, maker, year) values ('Camaro', 'Chevrolet', 1973);
insert into car (name, maker, year) values ('Express 3500', 'Chevrolet', 2006);
insert into car (name, maker, year) values ('Expedition EL', 'Ford', 2009);
insert into car (name, maker, year) values ('Acadia', 'GMC', 2007);
insert into car (name, maker, year) values ('Lucerne', 'Buick', 2008);
insert into car (name, maker, year) values ('Cobalt', 'Chevrolet', 2010);
insert into car (name, maker, year) values ('Rendezvous', 'Buick', 2004);
insert into car (name, maker, year) values ('R8', 'Audi', 2008);
insert into car (name, maker, year) values ('RX-7', 'Mazda', 1986);
insert into car (name, maker, year) values ('E-Class', 'Mercedes-Benz', 1993);
insert into car (name, maker, year) values ('4Runner', 'Toyota', 2001);
insert into car (name, maker, year) values ('Econoline E350', 'Ford', 1995);
insert into car (name, maker, year) values ('Escalade', 'Cadillac', 2004);
insert into car (name, maker, year) values ('Prius', 'Toyota', 2007);
insert into car (name, maker, year) values ('SL-Class', 'Mercedes-Benz', 2002);
insert into car (name, maker, year) values ('Ram Van 3500', 'Dodge', 1997);
insert into car (name, maker, year) values ('Accord', 'Honda', 1997);
insert into car (name, maker, year) values ('Rio', 'Kia', 2010);
insert into car (name, maker, year) values ('M-Class', 'Mercedes-Benz', 2004);
insert into car (name, maker, year) values ('Sierra 1500', 'GMC', 2012);
insert into car (name, maker, year) values ('599 GTB Fiorano', 'Ferrari', 2009);
insert into car (name, maker, year) values ('Defender', 'Land Rover', 1993);
insert into car (name, maker, year) values ('Silverado 3500', 'Chevrolet', 2008);
insert into car (name, maker, year) values ('Bonneville', 'Pontiac', 1992);
insert into car (name, maker, year) values ('Ram Van 3500', 'Dodge', 1997);
insert into car (name, maker, year) values ('Town Car', 'Lincoln', 2000);
insert into car (name, maker, year) values ('Vision', 'Eagle', 1994);
insert into car (name, maker, year) values ('Xterra', 'Nissan', 2003);
insert into car (name, maker, year) values ('Cavalier', 'Chevrolet', 2003);
insert into car (name, maker, year) values ('Silverado 1500', 'Chevrolet', 2003);
insert into car (name, maker, year) values ('S-Class', 'Mercedes-Benz', 1996);
insert into car (name, maker, year) values ('DB9', 'Aston Martin', 2008);
insert into car (name, maker, year) values ('Mazda6', 'Mazda', 2003);
insert into car (name, maker, year) values ('Quest', 'Nissan', 2009);
insert into car (name, maker, year) values ('Mirage', 'Mitsubishi', 2000);
insert into car (name, maker, year) values ('Town Car', 'Lincoln', 2000);
insert into car (name, maker, year) values ('Century', 'Buick', 2002);
insert into car (name, maker, year) values ('MR2', 'Toyota', 1987);
insert into car (name, maker, year) values ('599 GTB Fiorano', 'Ferrari', 2008);
insert into car (name, maker, year) values ('Blazer', 'Chevrolet', 2001);
insert into car (name, maker, year) values ('Galant', 'Mitsubishi', 1996);
insert into car (name, maker, year) values ('SLS AMG', 'Mercedes-Benz', 2012);
insert into car (name, maker, year) values ('Sebring', 'Chrysler', 2003);
insert into car (name, maker, year) values ('Range Rover', 'Land Rover', 1996);
insert into car (name, maker, year) values ('Civic', 'Honda', 2006);
insert into car (name, maker, year) values ('Sierra 3500', 'GMC', 2004);
insert into car (name, maker, year) values ('Club Wagon', 'Ford', 1993);
insert into car (name, maker, year) values ('Grand Voyager', 'Plymouth', 1995);
insert into car (name, maker, year) values ('SJ', 'Suzuki', 1993);
insert into car (name, maker, year) values ('Escalade ESV', 'Cadillac', 2006);
insert into car (name, maker, year) values ('Magnum', 'Dodge', 2005);
insert into car (name, maker, year) values ('Somerset', 'Buick', 1985);
insert into car (name, maker, year) values ('Diamante', 'Mitsubishi', 1997);
insert into car (name, maker, year) values ('Festiva', 'Ford', 1989);
insert into car (name, maker, year) values ('Charger', 'Dodge', 2012);
insert into car (name, maker, year) values ('Ridgeline', 'Honda', 2011);
insert into car (name, maker, year) values ('MDX', 'Acura', 2009);
insert into car (name, maker, year) values ('Grand Vitara', 'Suzuki', 2010);
insert into car (name, maker, year) values ('Reno', 'Suzuki', 2008);
insert into car (name, maker, year) values ('Concorde', 'Chrysler', 1996);
insert into car (name, maker, year) values ('Town Car', 'Lincoln', 1988);
insert into car (name, maker, year) values ('MDX', 'Acura', 2009);
insert into car (name, maker, year) values ('Veracruz', 'Hyundai', 2009);
insert into car (name, maker, year) values ('Truck', 'Mitsubishi', 1989);
insert into car (name, maker, year) values ('Echo', 'Toyota', 2002);
insert into car (name, maker, year) values ('88', 'Oldsmobile', 1997);
insert into car (name, maker, year) values ('MX-6', 'Mazda', 1996);
insert into car (name, maker, year) values ('2500', 'GMC', 1996);
insert into car (name, maker, year) values ('Element', 'Honda', 2003);
insert into car (name, maker, year) values ('Colorado', 'Chevrolet', 2012);
insert into car (name, maker, year) values ('F350', 'Ford', 2012);
insert into car (name, maker, year) values ('X3', 'BMW', 2011);
insert into car (name, maker, year) values ('Caprice', 'Chevrolet', 1977);
insert into car (name, maker, year) values ('MX-6', 'Mazda', 1988);
insert into car (name, maker, year) values ('Edge', 'Ford', 2011);
insert into car (name, maker, year) values ('GTI', 'Volkswagen', 1990);
insert into car (name, maker, year) values ('Lumina', 'Chevrolet', 2001);
insert into car (name, maker, year) values ('Lightning', 'Ford', 1994);
insert into car (name, maker, year) values ('Z4', 'BMW', 2008);
insert into car (name, maker, year) values ('MR2', 'Toyota', 2003);
insert into car (name, maker, year) values ('Accent', 'Hyundai', 2011);
insert into car (name, maker, year) values ('Montero', 'Mitsubishi', 2003);
insert into car (name, maker, year) values ('944', 'Porsche', 1991);
insert into car (name, maker, year) values ('MX-5', 'Mazda', 2011);
insert into car (name, maker, year) values ('SX4', 'Suzuki', 2010);
insert into car (name, maker, year) values ('DTS', 'Cadillac', 2006);
insert into car (name, maker, year) values ('Cabriolet', 'Volkswagen', 1995);
insert into car (name, maker, year) values ('Pathfinder', 'Nissan', 2000);
insert into car (name, maker, year) values ('4Runner', 'Toyota', 1996);
insert into car (name, maker, year) values ('H3', 'Hummer', 2009);
insert into car (name, maker, year) values ('Diamante', 'Mitsubishi', 1996);
insert into car (name, maker, year) values ('C70', 'Volvo', 2008);
insert into car (name, maker, year) values ('600', 'BMW', 1958);
insert into car (name, maker, year) values ('626', 'Mazda', 1985);
insert into car (name, maker, year) values ('E150', 'Ford', 2007);
insert into car (name, maker, year) values ('SSR', 'Chevrolet', 2005);
insert into car (name, maker, year) values ('IS', 'Lexus', 2011);
insert into car (name, maker, year) values ('F250', 'Ford', 2005);
insert into car (name, maker, year) values ('Aero 8', 'Morgan', 2009);
insert into car (name, maker, year) values ('Gemini', 'Pontiac', 1986);
insert into car (name, maker, year) values ('Sunfire', 'Pontiac', 1999);
insert into car (name, maker, year) values ('Continental', 'Lincoln', 2000);
insert into car (name, maker, year) values ('Continental Flying Spur', 'Bentley', 2006);
insert into car (name, maker, year) values ('S10', 'Chevrolet', 2001);
insert into car (name, maker, year) values ('Escalade ESV', 'Cadillac', 2007);
insert into car (name, maker, year) values ('Mazda6', 'Mazda', 2009);
insert into car (name, maker, year) values ('IS', 'Lexus', 2009);
insert into car (name, maker, year) values ('Yukon', 'GMC', 1995);
insert into car (name, maker, year) values ('ES', 'Lexus', 2004);
insert into car (name, maker, year) values ('Land Cruiser', 'Toyota', 2009);
insert into car (name, maker, year) values ('Freestyle', 'Ford', 2007);
insert into car (name, maker, year) values ('Titan', 'Nissan', 2011);
insert into car (name, maker, year) values ('Esperante', 'Panoz', 2006);
insert into car (name, maker, year) values ('Bonneville', 'Pontiac', 1991);
insert into car (name, maker, year) values ('G-Series 2500', 'Chevrolet', 1997);
insert into car (name, maker, year) values ('F-Series', 'Ford', 1996);
insert into car (name, maker, year) values ('3500 Club Coupe', 'GMC', 1995);
insert into car (name, maker, year) values ('MGB', 'MG', 1977);
insert into car (name, maker, year) values ('SLK-Class', 'Mercedes-Benz', 2010);
insert into car (name, maker, year) values ('G', 'Infiniti', 1999);
insert into car (name, maker, year) values ('X3', 'BMW', 2010);
insert into car (name, maker, year) values ('Integra', 'Acura', 1992);
insert into car (name, maker, year) values ('Familia', 'Mazda', 1990);
insert into car (name, maker, year) values ('Freestyle', 'Ford', 2006);
insert into car (name, maker, year) values ('M5', 'BMW', 2006);
insert into car (name, maker, year) values ('Mini', 'Austin', 1963);
insert into car (name, maker, year) values ('LeSabre', 'Buick', 1996);
insert into car (name, maker, year) values ('Mystique', 'Mercury', 1996);
insert into car (name, maker, year) values ('TL', 'Acura', 2009);
insert into car (name, maker, year) values ('Titan', 'Nissan', 2010);
insert into car (name, maker, year) values ('Escape', 'Ford', 2001);
insert into car (name, maker, year) values ('MKX', 'Lincoln', 2013);
insert into car (name, maker, year) values ('E-Series', 'Ford', 2011);
insert into car (name, maker, year) values ('Ram 1500 Club', 'Dodge', 1996);
insert into car (name, maker, year) values ('Camaro', 'Chevrolet', 2002);
insert into car (name, maker, year) values ('Coupe GT', 'Audi', 1985);
insert into car (name, maker, year) values ('Golf III', 'Volkswagen', 1995);
insert into car (name, maker, year) values ('Mustang', 'Ford', 1988);
insert into car (name, maker, year) values ('Daewoo Magnus', 'Suzuki', 2004);
insert into car (name, maker, year) values ('EX', 'Infiniti', 2010);
insert into car (name, maker, year) values ('Veracruz', 'Hyundai', 2007);
insert into car (name, maker, year) values ('Lancer Evolution', 'Mitsubishi', 2005);
insert into car (name, maker, year) values ('Cabriolet', 'Volkswagen', 1989);
insert into car (name, maker, year) values ('Sorento', 'Kia', 2012);
insert into car (name, maker, year) values ('Corolla', 'Toyota', 2012);
insert into car (name, maker, year) values ('Astro', 'Chevrolet', 2004);
insert into car (name, maker, year) values ('5000CS', 'Audi', 1987);
insert into car (name, maker, year) values ('Transit Connect', 'Ford', 2010);
insert into car (name, maker, year) values ('Mustang', 'Ford', 1995);
insert into car (name, maker, year) values ('Z4', 'BMW', 2008);
insert into car (name, maker, year) values ('G-Series 2500', 'Chevrolet', 1996);
insert into car (name, maker, year) values ('4Runner', 'Toyota', 1995);
insert into car (name, maker, year) values ('Amigo', 'Isuzu', 2000);
insert into car (name, maker, year) values ('MPV', 'Mazda', 1989);
insert into car (name, maker, year) values ('Concorde', 'Chrysler', 2004);
insert into car (name, maker, year) values ('V8 Vantage', 'Aston Martin', 2006);
insert into car (name, maker, year) values ('Dakota Club', 'Dodge', 2005);
insert into car (name, maker, year) values ('Terraza', 'Buick', 2005);
insert into car (name, maker, year) values ('SC', 'Lexus', 1994);
insert into car (name, maker, year) values ('Intrepid', 'Dodge', 1995);
insert into car (name, maker, year) values ('Astro', 'Chevrolet', 1995);
insert into car (name, maker, year) values ('Verona', 'Suzuki', 2005);
insert into car (name, maker, year) values ('F150', 'Ford', 1997);
insert into car (name, maker, year) values ('Passat', 'Volkswagen', 2012);
insert into car (name, maker, year) values ('Ascender', 'Isuzu', 2005);
insert into car (name, maker, year) values ('GTI', 'Volkswagen', 2008);
insert into car (name, maker, year) values ('Supra', 'Toyota', 1992);
insert into car (name, maker, year) values ('BRZ', 'Subaru', 2013);
insert into car (name, maker, year) values ('7 Series', 'BMW', 2005);
insert into car (name, maker, year) values ('Cooper Countryman', 'MINI', 2011);
insert into car (name, maker, year) values ('Vantage', 'Aston Martin', 2008);
insert into car (name, maker, year) values ('Sorento', 'Kia', 2009);
insert into car (name, maker, year) values ('VS Commodore', 'Holden', 1996);
insert into car (name, maker, year) values ('Flex', 'Ford', 2009);
insert into car (name, maker, year) values ('R8', 'Audi', 2010);
insert into car (name, maker, year) values ('D350 Club', 'Dodge', 1992);
insert into car (name, maker, year) values ('Civic', 'Honda', 1992);
insert into car (name, maker, year) values ('Crown Victoria', 'Ford', 2006);
insert into car (name, maker, year) values ('C70', 'Volvo', 2003);
insert into car (name, maker, year) values ('V40', 'Volvo', 2001);
insert into car (name, maker, year) values ('Diamante', 'Mitsubishi', 1996);
insert into car (name, maker, year) values ('Z4 M', 'BMW', 2009);
insert into car (name, maker, year) values ('Santa Fe', 'Hyundai', 2001);
insert into car (name, maker, year) values ('Wrangler', 'Jeep', 1998);
insert into car (name, maker, year) values ('Corvette', 'Chevrolet', 1978);
insert into car (name, maker, year) values ('RX', 'Lexus', 2008);
insert into car (name, maker, year) values ('Diamante', 'Mitsubishi', 1992);
insert into car (name, maker, year) values ('6000', 'Pontiac', 1990);
insert into car (name, maker, year) values ('LR3', 'Land Rover', 2006);
insert into car (name, maker, year) values ('Murano', 'Nissan', 2005);
insert into car (name, maker, year) values ('Trans Sport', 'Pontiac', 1995);
insert into car (name, maker, year) values ('430 Scuderia', 'Ferrari', 2009);
insert into car (name, maker, year) values ('S-Series', 'Saturn', 1994);
insert into car (name, maker, year) values ('SC', 'Lexus', 1995);
insert into car (name, maker, year) values ('Regal', 'Buick', 2004);
insert into car (name, maker, year) values ('Ram Van 1500', 'Dodge', 1999);
insert into car (name, maker, year) values ('Tribute', 'Mazda', 2006);
insert into car (name, maker, year) values ('H1', 'Hummer', 2004);
insert into car (name, maker, year) values ('Continental', 'Lincoln', 1992);
insert into car (name, maker, year) values ('Stealth', 'Dodge', 1995);
insert into car (name, maker, year) values ('Elan', 'Lotus', 1991);
insert into car (name, maker, year) values ('Escalade ESV', 'Cadillac', 2003);
insert into car (name, maker, year) values ('Edge', 'Ford', 2009);
insert into car (name, maker, year) values ('Tiguan', 'Volkswagen', 2010);
insert into car (name, maker, year) values ('Elise', 'Lotus', 2011);
insert into car (name, maker, year) values ('Sonoma', 'GMC', 2003);
insert into car (name, maker, year) values ('GTI', 'Volkswagen', 1990);
insert into car (name, maker, year) values ('911', 'Porsche', 2011);
insert into car (name, maker, year) values ('Bronco', 'Ford', 1987);
insert into car (name, maker, year) values ('Astra', 'Saturn', 2008);
insert into car (name, maker, year) values ('Civic', 'Honda', 1996);
insert into car (name, maker, year) values ('Optima', 'Kia', 2012);
insert into car (name, maker, year) values ('TL', 'Acura', 2006);
insert into car (name, maker, year) values ('Passat', 'Volkswagen', 2004);
insert into car (name, maker, year) values ('Camaro', 'Chevrolet', 2011);
insert into car (name, maker, year) values ('98', 'Oldsmobile', 1994);
insert into car (name, maker, year) values ('Ram 1500', 'Dodge', 2006);
insert into car (name, maker, year) values ('Azure', 'Bentley', 2008);
insert into car (name, maker, year) values ('Silverado', 'Chevrolet', 1999);
insert into car (name, maker, year) values ('300C', 'Chrysler', 2005);
insert into car (name, maker, year) values ('LX', 'Lexus', 2002);
insert into car (name, maker, year) values ('190E', 'Mercedes-Benz', 1993);
insert into car (name, maker, year) values ('Taurus', 'Ford', 1993);
insert into car (name, maker, year) values ('A5', 'Audi', 2012);
insert into car (name, maker, year) values ('G-Series 3500', 'Chevrolet', 1998);
insert into car (name, maker, year) values ('Journey', 'Dodge', 2011);
insert into car (name, maker, year) values ('G35', 'Infiniti', 2006);
insert into car (name, maker, year) values ('Camry Hybrid', 'Toyota', 2012);
insert into car (name, maker, year) values ('B-Series', 'Mazda', 1997);
insert into car (name, maker, year) values ('Bravada', 'Oldsmobile', 1993);
insert into car (name, maker, year) values ('Rally Wagon 2500', 'GMC', 1994);
insert into car (name, maker, year) values ('850', 'Volvo', 1994);
insert into car (name, maker, year) values ('Sunfire', 'Pontiac', 1996);
insert into car (name, maker, year) values ('Tribeca', 'Subaru', 2009);
insert into car (name, maker, year) values ('G-Series G30', 'Chevrolet', 1995);
insert into car (name, maker, year) values ('Spider', 'Alfa Romeo', 1992);
insert into car (name, maker, year) values ('Samurai', 'Suzuki', 1994);
insert into car (name, maker, year) values ('Ram', 'Dodge', 2003);
insert into car (name, maker, year) values ('Tracker', 'Chevrolet', 2002);
insert into car (name, maker, year) values ('Topaz', 'Mercury', 1993);
insert into car (name, maker, year) values ('Phantom', 'Rolls-Royce', 2013);
insert into car (name, maker, year) values ('Protege', 'Mazda', 2001);
insert into car (name, maker, year) values ('Land Cruiser', 'Toyota', 1995);
insert into car (name, maker, year) values ('3500 Club Coupe', 'GMC', 1993);
insert into car (name, maker, year) values ('DB9', 'Aston Martin', 2009);
insert into car (name, maker, year) values ('3500', 'Chevrolet', 1992);
insert into car (name, maker, year) values ('Sienna', 'Toyota', 1998);
insert into car (name, maker, year) values ('Boxster', 'Porsche', 2003);
insert into car (name, maker, year) values ('Jetta', 'Volkswagen', 2012);
insert into car (name, maker, year) values ('Legend', 'Acura', 1992);
insert into car (name, maker, year) values ('Catera', 'Cadillac', 1997);
insert into car (name, maker, year) values ('CTS', 'Cadillac', 2008);
insert into car (name, maker, year) values ('Mulsanne', 'Bentley', 2012);
insert into car (name, maker, year) values ('C70', 'Volvo', 2001);
insert into car (name, maker, year) values ('CTS', 'Cadillac', 2008);
insert into car (name, maker, year) values ('Grand Vitara', 'Suzuki', 2011);
insert into car (name, maker, year) values ('Outback', 'Subaru', 2000);
insert into car (name, maker, year) values ('Silverado 2500', 'Chevrolet', 2010);
insert into car (name, maker, year) values ('Corvette', 'Chevrolet', 2003);
insert into car (name, maker, year) values ('RAV4', 'Toyota', 2005);
insert into car (name, maker, year) values ('Tracker', 'Chevrolet', 1998);
insert into car (name, maker, year) values ('Altima', 'Nissan', 1997);
insert into car (name, maker, year) values ('370Z', 'Nissan', 2010);
insert into car (name, maker, year) values ('Accord', 'Honda', 1997);
insert into car (name, maker, year) values ('Type 2', 'Volkswagen', 1990);
insert into car (name, maker, year) values ('Galant', 'Mitsubishi', 1992);
insert into car (name, maker, year) values ('Mustang', 'Ford', 1986);
insert into car (name, maker, year) values ('Grand Voyager', 'Plymouth', 1993);
insert into car (name, maker, year) values ('Cabriolet', 'Volkswagen', 2001);
insert into car (name, maker, year) values ('Escape', 'Ford', 2005);
insert into car (name, maker, year) values ('9-3', 'Saab', 2007);
insert into car (name, maker, year) values ('Metro', 'Geo', 1996);
insert into car (name, maker, year) values ('Explorer Sport Trac', 'Ford', 2008);
insert into car (name, maker, year) values ('Safari', 'GMC', 2003);
insert into car (name, maker, year) values ('Quest', 'Nissan', 1997);
insert into car (name, maker, year) values ('300SD', 'Mercedes-Benz', 1992);
insert into car (name, maker, year) values ('Commander', 'Jeep', 2010);
insert into car (name, maker, year) values ('Leganza', 'Daewoo', 1999);
insert into car (name, maker, year) values ('Fortwo', 'Smart', 2011);
insert into car (name, maker, year) values ('Boxster', 'Porsche', 2010);
insert into car (name, maker, year) values ('Continental', 'Bentley', 2010);
insert into car (name, maker, year) values ('Town & Country', 'Chrysler', 2011);
insert into car (name, maker, year) values ('Explorer', 'Ford', 2007);
insert into car (name, maker, year) values ('Topaz', 'Mercury', 1987);
insert into car (name, maker, year) values ('Boxster', 'Porsche', 2002);
insert into car (name, maker, year) values ('Outlander', 'Mitsubishi', 2012);
insert into car (name, maker, year) values ('Range Rover', 'Land Rover', 2006);
insert into car (name, maker, year) values ('Outback', 'Subaru', 2008);
insert into car (name, maker, year) values ('Z4', 'BMW', 2008);
insert into car (name, maker, year) values ('CTS-V', 'Cadillac', 2012);
insert into car (name, maker, year) values ('RSX', 'Acura', 2006);
insert into car (name, maker, year) values ('Galant', 'Mitsubishi', 1987);
insert into car (name, maker, year) values ('7 Series', 'BMW', 2011);
insert into car (name, maker, year) values ('Pilot', 'Honda', 2008);
insert into car (name, maker, year) values ('Montero', 'Mitsubishi', 1998);
insert into car (name, maker, year) values ('TL', 'Acura', 2007);
insert into car (name, maker, year) values ('LX', 'Lexus', 2011);
insert into car (name, maker, year) values ('Suburban 2500', 'Chevrolet', 1998);
insert into car (name, maker, year) values ('GTO', 'Mitsubishi', 1991);
insert into car (name, maker, year) values ('Grand Prix', 'Pontiac', 1970);
insert into car (name, maker, year) values ('Eldorado', 'Cadillac', 1997);
insert into car (name, maker, year) values ('Protege', 'Mazda', 1992);
insert into car (name, maker, year) values ('LeSabre', 'Buick', 1997);
insert into car (name, maker, year) values ('Cherokee', 'Jeep', 1999);
insert into car (name, maker, year) values ('Bonneville', 'Pontiac', 1993);
insert into car (name, maker, year) values ('929', 'Mazda', 1992);
insert into car (name, maker, year) values ('911', 'Porsche', 1991);
insert into car (name, maker, year) values ('Altima', 'Nissan', 2010);
insert into car (name, maker, year) values ('Town & Country', 'Chrysler', 2006);
insert into car (name, maker, year) values ('Altima', 'Nissan', 1998);
insert into car (name, maker, year) values ('Venza', 'Toyota', 2009);
insert into car (name, maker, year) values ('V8 Vantage', 'Aston Martin', 2007);
insert into car (name, maker, year) values ('Galant', 'Mitsubishi', 2012);
insert into car (name, maker, year) values ('Explorer', 'Ford', 1993);
insert into car (name, maker, year) values ('Axiom', 'Isuzu', 2004);
insert into car (name, maker, year) values ('Grand Am', 'Pontiac', 1987);
insert into car (name, maker, year) values ('Suburban 1500', 'GMC', 1998);
insert into car (name, maker, year) values ('B-Series', 'Mazda', 1988);
insert into car (name, maker, year) values ('Mustang', 'Ford', 1988);
insert into car (name, maker, year) values ('GTI', 'Volkswagen', 1985);
insert into car (name, maker, year) values ('G', 'Infiniti', 2001);
insert into car (name, maker, year) values ('Azure T', 'Bentley', 2010);
insert into car (name, maker, year) values ('Xterra', 'Nissan', 2009);
insert into car (name, maker, year) values ('F350', 'Ford', 2011);
insert into car (name, maker, year) values ('Grand Vitara', 'Suzuki', 2012);
insert into car (name, maker, year) values ('Civic', 'Honda', 2005);
insert into car (name, maker, year) values ('E-Series', 'Ford', 1991);
insert into car (name, maker, year) values ('Ram 3500', 'Dodge', 1997);
insert into car (name, maker, year) values ('Sentra', 'Nissan', 1991);
insert into car (name, maker, year) values ('MKS', 'Lincoln', 2012);
insert into car (name, maker, year) values ('Impreza', 'Subaru', 1993);
insert into car (name, maker, year) values ('Sentra', 'Nissan', 2002);
insert into car (name, maker, year) values ('Impala', 'Chevrolet', 2003);
insert into car (name, maker, year) values ('XC90', 'Volvo', 2008);
insert into car (name, maker, year) values ('90', 'Audi', 1990);
insert into car (name, maker, year) values ('Somerset', 'Buick', 1986);
insert into car (name, maker, year) values ('Ram 1500', 'Dodge', 2008);
insert into car (name, maker, year) values ('Corvette', 'Chevrolet', 1992);
insert into car (name, maker, year) values ('Impreza', 'Subaru', 2002);
insert into car (name, maker, year) values ('S40', 'Volvo', 2006);
insert into car (name, maker, year) values ('Express 3500', 'Chevrolet', 2010);
insert into car (name, maker, year) values ('Durango', 'Dodge', 1999);
insert into car (name, maker, year) values ('XG300', 'Hyundai', 2001);
insert into car (name, maker, year) values ('DB9', 'Aston Martin', 2005);
insert into car (name, maker, year) values ('X5', 'BMW', 2009);
insert into car (name, maker, year) values ('CTS-V', 'Cadillac', 2009);
insert into car (name, maker, year) values ('Windstar', 'Ford', 2002);
insert into car (name, maker, year) values ('Nitro', 'Dodge', 2008);
insert into car (name, maker, year) values ('Mountaineer', 'Mercury', 1998);
insert into car (name, maker, year) values ('Explorer', 'Ford', 1996);
insert into car (name, maker, year) values ('Escape', 'Ford', 2012);
insert into car (name, maker, year) values ('Tempest', 'Pontiac', 1961);
insert into car (name, maker, year) values ('Quest', 'Nissan', 2005);
insert into car (name, maker, year) values ('MX-5', 'Mazda', 2003);
insert into car (name, maker, year) values ('Grand Prix', 'Pontiac', 1972);
insert into car (name, maker, year) values ('Prelude', 'Honda', 1997);
insert into car (name, maker, year) values ('911', 'Porsche', 2010);
insert into car (name, maker, year) values ('M3', 'BMW', 2009);
insert into car (name, maker, year) values ('Swift', 'Suzuki', 1990);
insert into car (name, maker, year) values ('Park Avenue', 'Buick', 1996);
insert into car (name, maker, year) values ('Corvette', 'Chevrolet', 1993);
insert into car (name, maker, year) values ('Pathfinder', 'Nissan', 2011);
insert into car (name, maker, year) values ('riolet', 'Audi', 1995);
insert into car (name, maker, year) values ('New Yorker', 'Chrysler', 1993);
insert into car (name, maker, year) values ('Savana 3500', 'GMC', 2002);
insert into car (name, maker, year) values ('Stratus', 'Dodge', 2001);
insert into car (name, maker, year) values ('7 Series', 'BMW', 2008);
insert into car (name, maker, year) values ('E350', 'Ford', 2010);
insert into car (name, maker, year) values ('Ram Wagon B150', 'Dodge', 1992);
insert into car (name, maker, year) values ('Tahoe', 'Chevrolet', 1998);
insert into car (name, maker, year) values ('Cabriolet', 'Volkswagen', 1999);
insert into car (name, maker, year) values ('Aero 8', 'Morgan', 2006);
insert into car (name, maker, year) values ('Freelander', 'Land Rover', 2011);
insert into car (name, maker, year) values ('LS', 'Lexus', 2003);
insert into car (name, maker, year) values ('Solara', 'Toyota', 2002);
insert into car (name, maker, year) values ('Ram 1500', 'Dodge', 2008);
insert into car (name, maker, year) values ('CR-V', 'Honda', 2003);
insert into car (name, maker, year) values ('Galant', 'Mitsubishi', 2008);
insert into car (name, maker, year) values ('rio', 'Volkswagen', 1998);
insert into car (name, maker, year) values ('5 Series', 'BMW', 1999);
insert into car (name, maker, year) values ('MX-6', 'Mazda', 1993);
insert into car (name, maker, year) values ('Bonneville', 'Pontiac', 2000);
insert into car (name, maker, year) values ('Yukon', 'GMC', 2004);
insert into car (name, maker, year) values ('Outlook', 'Saturn', 2009);
insert into car (name, maker, year) values ('TT', 'Audi', 2011);
insert into car (name, maker, year) values ('XJ', 'Jaguar', 2010);
insert into car (name, maker, year) values ('Thunderbird', 'Ford', 1980);
insert into car (name, maker, year) values ('300E', 'Mercedes-Benz', 1992);
insert into car (name, maker, year) values ('Corolla', 'Toyota', 2006);
insert into car (name, maker, year) values ('SLX', 'Acura', 1999);
insert into car (name, maker, year) values ('Grand Am', 'Pontiac', 1988);
insert into car (name, maker, year) values ('3 Series', 'BMW', 2000);
insert into car (name, maker, year) values ('Sonata', 'Hyundai', 1994);
insert into car (name, maker, year) values ('C-Class', 'Mercedes-Benz', 2010);
insert into car (name, maker, year) values ('LTD Crown Victoria', 'Ford', 1993);
insert into car (name, maker, year) values ('B-Series', 'Mazda', 1990);
insert into car (name, maker, year) values ('Ram 3500', 'Dodge', 2005);
insert into car (name, maker, year) values ('928', 'Porsche', 1993);
insert into car (name, maker, year) values ('MR2', 'Toyota', 1993);
insert into car (name, maker, year) values ('E250', 'Ford', 1984);
insert into car (name, maker, year) values ('Fiero', 'Pontiac', 1988);
insert into car (name, maker, year) values ('W201', 'Mercedes-Benz', 1985);
insert into car (name, maker, year) values ('SC', 'Lexus', 2010);
insert into car (name, maker, year) values ('Town Car', 'Lincoln', 2011);
insert into car (name, maker, year) values ('Equus', 'Hyundai', 2013);
insert into car (name, maker, year) values ('2500 Club Coupe', 'GMC', 1998);
insert into car (name, maker, year) values ('Eclipse', 'Mitsubishi', 1991);
insert into car (name, maker, year) values ('C-Class', 'Mercedes-Benz', 2006);
insert into car (name, maker, year) values ('Legend', 'Acura', 1990);
insert into car (name, maker, year) values ('7 Series', 'BMW', 2001);
insert into car (name, maker, year) values ('Montero', 'Mitsubishi', 1995);
insert into car (name, maker, year) values ('C30', 'Volvo', 2012);
insert into car (name, maker, year) values ('Odyssey', 'Honda', 2007);
insert into car (name, maker, year) values ('RAV4', 'Toyota', 2005);
insert into car (name, maker, year) values ('Silverado 3500', 'Chevrolet', 2006);
insert into car (name, maker, year) values ('Monterey', 'Mercury', 2007);
insert into car (name, maker, year) values ('Freelander', 'Land Rover', 2002);
insert into car (name, maker, year) values ('M Roadster', 'BMW', 2006);
insert into car (name, maker, year) values ('Silverado 1500', 'Chevrolet', 2008);
insert into car (name, maker, year) values ('Trans Sport', 'Pontiac', 1997);
insert into car (name, maker, year) values ('LS', 'Lexus', 2012);
insert into car (name, maker, year) values ('Cougar', 'Mercury', 1967);
insert into car (name, maker, year) values ('F-Series', 'Ford', 2004);
insert into car (name, maker, year) values ('Escalade EXT', 'Cadillac', 2007);
insert into car (name, maker, year) values ('SC', 'Lexus', 1996);
insert into car (name, maker, year) values ('MKZ', 'Lincoln', 2010);
insert into car (name, maker, year) values ('Rodeo', 'Isuzu', 2000);
insert into car (name, maker, year) values ('GTI', 'Volkswagen', 2002);
insert into car (name, maker, year) values ('2500', 'GMC', 1998);
insert into car (name, maker, year) values ('Grand Cherokee', 'Jeep', 2001);
insert into car (name, maker, year) values ('Trooper', 'Isuzu', 1997);
insert into car (name, maker, year) values ('NSX', 'Acura', 1993);
insert into car (name, maker, year) values ('S-Series', 'Saturn', 1996);
insert into car (name, maker, year) values ('Viper', 'Dodge', 2002);
insert into car (name, maker, year) values ('Sunbird', 'Pontiac', 1984);
insert into car (name, maker, year) values ('S5', 'Audi', 2009);
insert into car (name, maker, year) values ('E150', 'Ford', 2009);
insert into car (name, maker, year) values ('Villager', 'Mercury', 1993);
insert into car (name, maker, year) values ('Tracker', 'Chevrolet', 2000);
insert into car (name, maker, year) values ('E-Class', 'Mercedes-Benz', 1991);
insert into car (name, maker, year) values ('745', 'BMW', 2004);
insert into car (name, maker, year) values ('Q5', 'Audi', 2010);
insert into car (name, maker, year) values ('rio', 'Volkswagen', 2001);
insert into car (name, maker, year) values ('Fleetwood', 'Cadillac', 1996);
insert into car (name, maker, year) values ('S-Series', 'Saturn', 1999);
insert into car (name, maker, year) values ('Xterra', 'Nissan', 2004);
insert into car (name, maker, year) values ('Capri', 'Mercury', 1992);
insert into car (name, maker, year) values ('Chariot', 'Mitsubishi', 1987);
insert into car (name, maker, year) values ('Titan', 'Nissan', 2009);
insert into car (name, maker, year) values ('Alcyone SVX', 'Subaru', 1993);
insert into car (name, maker, year) values ('Raider', 'Mitsubishi', 2009);
insert into car (name, maker, year) values ('Galant', 'Mitsubishi', 1999);
insert into car (name, maker, year) values ('Avenger', 'Dodge', 1997);
insert into car (name, maker, year) values ('Mirage', 'Mitsubishi', 1988);
insert into car (name, maker, year) values ('Legacy', 'Subaru', 1995);
insert into car (name, maker, year) values ('Liberty', 'Jeep', 2009);
insert into car (name, maker, year) values ('LTD', 'Ford', 1985);
insert into car (name, maker, year) values ('Traverse', 'Chevrolet', 2010);
insert into car (name, maker, year) values ('Corolla', 'Toyota', 2003);
insert into car (name, maker, year) values ('E150', 'Ford', 2010);
insert into car (name, maker, year) values ('Wrangler', 'Jeep', 2002);
insert into car (name, maker, year) values ('5 Series', 'BMW', 2010);
insert into car (name, maker, year) values ('TrailBlazer', 'Chevrolet', 2005);
insert into car (name, maker, year) values ('500', 'Fiat', 2012);
insert into car (name, maker, year) values ('Z3', 'BMW', 1997);
insert into car (name, maker, year) values ('Yaris', 'Toyota', 2006);
insert into car (name, maker, year) values ('GTI', 'Volkswagen', 1998);
insert into car (name, maker, year) values ('Grand Voyager', 'Plymouth', 1993);
insert into car (name, maker, year) values ('Laser', 'Plymouth', 1990);
insert into car (name, maker, year) values ('GS', 'Lexus', 1996);
insert into car (name, maker, year) values ('LHS', 'Chrysler', 1995);
insert into car (name, maker, year) values ('SC', 'Lexus', 1998);
insert into car (name, maker, year) values ('A4', 'Audi', 2003);
insert into car (name, maker, year) values ('Crown Victoria', 'Ford', 2002);
insert into car (name, maker, year) values ('Dakota Club', 'Dodge', 1995);
insert into car (name, maker, year) values ('Lancer', 'Mitsubishi', 2002);
insert into car (name, maker, year) values ('Grand Prix', 'Pontiac', 1965);
insert into car (name, maker, year) values ('4000s', 'Audi', 1986);
insert into car (name, maker, year) values ('Amanti', 'Kia', 2009);
insert into car (name, maker, year) values ('EXP', 'Ford', 1984);
insert into car (name, maker, year) values ('3000GT', 'Mitsubishi', 1997);
insert into car (name, maker, year) values ('B-Series Plus', 'Mazda', 1993);
insert into car (name, maker, year) values ('Legend', 'Acura', 1993);
insert into car (name, maker, year) values ('Equus', 'Hyundai', 2013);
insert into car (name, maker, year) values ('Dakota', 'Dodge', 2002);
insert into car (name, maker, year) values ('Corvette', 'Chevrolet', 1960);
insert into car (name, maker, year) values ('IS', 'Lexus', 2004);
insert into car (name, maker, year) values ('G', 'Infiniti', 1996);
insert into car (name, maker, year) values ('Tahoe', 'Chevrolet', 1996);
insert into car (name, maker, year) values ('Mighty Max Macro', 'Mitsubishi', 1992);
insert into car (name, maker, year) values ('DTS', 'Cadillac', 2010);
insert into car (name, maker, year) values ('Precis', 'Mitsubishi', 1986);
insert into car (name, maker, year) values ('Daewoo Kalos', 'Pontiac', 2006);
insert into car (name, maker, year) values ('IS-F', 'Lexus', 2010);
insert into car (name, maker, year) values ('RAV4', 'Toyota', 2008);
insert into car (name, maker, year) values ('Sonoma Club Coupe', 'GMC', 1997);
insert into car (name, maker, year) values ('Grand Caravan', 'Dodge', 2000);
insert into car (name, maker, year) values ('Diamante', 'Mitsubishi', 2000);
insert into car (name, maker, year) values ('Camry Hybrid', 'Toyota', 2010);
insert into car (name, maker, year) values ('Aspen', 'Chrysler', 2007);
insert into car (name, maker, year) values ('Marauder', 'Mercury', 2003);
insert into car (name, maker, year) values ('i-370', 'Isuzu', 2008);
insert into car (name, maker, year) values ('300E', 'Mercedes-Benz', 1993);
insert into car (name, maker, year) values ('ZX2', 'Ford', 2001);
insert into car (name, maker, year) values ('Astro', 'Chevrolet', 1999);
insert into car (name, maker, year) values ('TT', 'Audi', 2002);
insert into car (name, maker, year) values ('Town Car', 'Lincoln', 1984);
insert into car (name, maker, year) values ('Sebring', 'Chrysler', 1997);
insert into car (name, maker, year) values ('RS 4', 'Audi', 2007);
insert into car (name, maker, year) values ('Astro', 'Chevrolet', 2002);
insert into car (name, maker, year) values ('Legacy', 'Subaru', 2008);
insert into car (name, maker, year) values ('Accent', 'Hyundai', 2006);
insert into car (name, maker, year) values ('Daewoo Kalos', 'Pontiac', 2005);
insert into car (name, maker, year) values ('DB9', 'Aston Martin', 2011);
insert into car (name, maker, year) values ('Boxster', 'Porsche', 2009);
insert into car (name, maker, year) values ('Murano', 'Nissan', 2010);
insert into car (name, maker, year) values ('F150', 'Ford', 2008);
insert into car (name, maker, year) values ('SLK-Class', 'Mercedes-Benz', 2001);
insert into car (name, maker, year) values ('Ram 1500 Club', 'Dodge', 2001);
insert into car (name, maker, year) values ('A6', 'Audi', 2007);
insert into car (name, maker, year) values ('Grand Am', 'Pontiac', 1987);
insert into car (name, maker, year) values ('C-Class', 'Mercedes-Benz', 2007);
insert into car (name, maker, year) values ('E-Class', 'Mercedes-Benz', 2012);
insert into car (name, maker, year) values ('Murciélago', 'Lamborghini', 2008);
insert into car (name, maker, year) values ('Monte Carlo', 'Chevrolet', 2003);
insert into car (name, maker, year) values ('Prius', 'Toyota', 2005);
insert into car (name, maker, year) values ('Chariot', 'Mitsubishi', 1990);
insert into car (name, maker, year) values ('XL-7', 'Suzuki', 2006);
insert into car (name, maker, year) values ('LS', 'Lexus', 1992);
insert into car (name, maker, year) values ('Ram 2500', 'Dodge', 2008);
insert into car (name, maker, year) values ('Millenia', 'Mazda', 2000);
insert into car (name, maker, year) values ('S60', 'Volvo', 2010);
insert into car (name, maker, year) values ('6 Series', 'BMW', 2010);
insert into car (name, maker, year) values ('Traverse', 'Chevrolet', 2010);
insert into car (name, maker, year) values ('Forester', 'Subaru', 2001);
insert into car (name, maker, year) values ('Escalade EXT', 'Cadillac', 2004);
insert into car (name, maker, year) values ('Silverado 1500', 'Chevrolet', 2002);
insert into car (name, maker, year) values ('Grand Vitara', 'Suzuki', 2011);
insert into car (name, maker, year) values ('Corvette', 'Chevrolet', 2009);
insert into car (name, maker, year) values ('Malibu', 'Chevrolet', 2006);
insert into car (name, maker, year) values ('VehiCROSS', 'Isuzu', 1999);
insert into car (name, maker, year) values ('A6', 'Audi', 2002);
insert into car (name, maker, year) values ('Yukon XL 2500', 'GMC', 2005);
insert into car (name, maker, year) values ('Festiva', 'Ford', 1992);
insert into car (name, maker, year) values ('Malibu', 'Chevrolet', 2004);
insert into car (name, maker, year) values ('Yaris', 'Toyota', 2011);
insert into car (name, maker, year) values ('Diablo', 'Lamborghini', 1998);
insert into car (name, maker, year) values ('B-Series Plus', 'Mazda', 1999);
insert into car (name, maker, year) values ('Esprit', 'Lotus', 2004);
insert into car (name, maker, year) values ('Ram 1500 Club', 'Dodge', 1995);
insert into car (name, maker, year) values ('Continental Mark VII', 'Lincoln', 1989);
insert into car (name, maker, year) values ('Toronado', 'Oldsmobile', 1992);
insert into car (name, maker, year) values ('599 GTB Fiorano', 'Ferrari', 2009);
insert into car (name, maker, year) values ('Taurus', 'Ford', 1989);
insert into car (name, maker, year) values ('Xterra', 'Nissan', 2001);
insert into car (name, maker, year) values ('Safari', 'Pontiac', 1987);
insert into car (name, maker, year) values ('Sequoia', 'Toyota', 2004);
insert into car (name, maker, year) values ('Suburban 1500', 'GMC', 1996);
insert into car (name, maker, year) values ('Murciélago', 'Lamborghini', 2003);
insert into car (name, maker, year) values ('RVR', 'Mitsubishi', 1993);
insert into car (name, maker, year) values ('Sonoma', 'GMC', 2003);
insert into car (name, maker, year) values ('Econoline E250', 'Ford', 1999);
insert into car (name, maker, year) values ('GTI', 'Volkswagen', 1997);
insert into car (name, maker, year) values ('Tundra', 'Toyota', 2001);
insert into car (name, maker, year) values ('I', 'Infiniti', 2000);
insert into car (name, maker, year) values ('Explorer', 'Ford', 2000);
insert into car (name, maker, year) values ('Yukon XL 2500', 'GMC', 2011);
insert into car (name, maker, year) values ('Ipsum', 'Toyota', 2000);
insert into car (name, maker, year) values ('EXP', 'Ford', 1988);
insert into car (name, maker, year) values ('Express 2500', 'Chevrolet', 2002);
insert into car (name, maker, year) values ('Optima', 'Kia', 2006);
insert into car (name, maker, year) values ('S-Series', 'Saturn', 1998);
insert into car (name, maker, year) values ('Legend', 'Acura', 1995);
insert into car (name, maker, year) values ('Suburban 2500', 'GMC', 1998);
insert into car (name, maker, year) values ('370Z', 'Nissan', 2012);
insert into car (name, maker, year) values ('Monterey', 'Mercury', 2007);
insert into car (name, maker, year) values ('Park Avenue', 'Buick', 2000);
insert into car (name, maker, year) values ('Navigator', 'Lincoln', 2006);
insert into car (name, maker, year) values ('5 Series', 'BMW', 2004);
insert into car (name, maker, year) values ('Z3', 'BMW', 1998);
insert into car (name, maker, year) values ('Caprice', 'Chevrolet', 1994);
insert into car (name, maker, year) values ('Sierra 1500', 'GMC', 2012);
insert into car (name, maker, year) values ('Express 3500', 'Chevrolet', 1999);
insert into car (name, maker, year) values ('Escalade', 'Cadillac', 1999);
insert into car (name, maker, year) values ('Sunbird', 'Pontiac', 1992);
insert into car (name, maker, year) values ('Eurovan', 'Volkswagen', 1993);
insert into car (name, maker, year) values ('GX', 'Lexus', 2011);
insert into car (name, maker, year) values ('Venture', 'Chevrolet', 2002);
insert into car (name, maker, year) values ('62', 'Maybach', 2003);
insert into car (name, maker, year) values ('Ram Van B350', 'Dodge', 1992);
insert into car (name, maker, year) values ('Mazda6', 'Mazda', 2012);
insert into car (name, maker, year) values ('FX', 'Infiniti', 2003);
insert into car (name, maker, year) values ('Ascender', 'Isuzu', 2006);
insert into car (name, maker, year) values ('Express 2500', 'Chevrolet', 1998);
insert into car (name, maker, year) values ('Sidekick', 'Suzuki', 1998);
insert into car (name, maker, year) values ('Sonoma', 'GMC', 1999);
insert into car (name, maker, year) values ('Vibe', 'Pontiac', 2005);
insert into car (name, maker, year) values ('Altima', 'Nissan', 1998);
insert into car (name, maker, year) values ('Sedona', 'Kia', 2003);
insert into car (name, maker, year) values ('E-Class', 'Mercedes-Benz', 1985);
insert into car (name, maker, year) values ('Savana', 'GMC', 2008);
insert into car (name, maker, year) values ('Fit', 'Honda', 2008);
insert into car (name, maker, year) values ('Ram Van 1500', 'Dodge', 2003);
insert into car (name, maker, year) values ('Yukon XL 1500', 'GMC', 2010);
insert into car (name, maker, year) values ('Aventador', 'Lamborghini', 2012);
insert into car (name, maker, year) values ('Explorer', 'Ford', 2006);
insert into car (name, maker, year) values ('Freelander', 'Land Rover', 2005);
insert into car (name, maker, year) values ('Corvette', 'Chevrolet', 1967);
insert into car (name, maker, year) values ('Skylark', 'Buick', 1988);
insert into car (name, maker, year) values ('Yukon', 'GMC', 1993);
insert into car (name, maker, year) values ('CR-V', 'Honda', 2011);
insert into car (name, maker, year) values ('Lancer', 'Mitsubishi', 2011);
insert into car (name, maker, year) values ('Ram Van 1500', 'Dodge', 1998);
insert into car (name, maker, year) values ('Bonneville', 'Pontiac', 2004);
insert into car (name, maker, year) values ('L-Series', 'Saturn', 2002);
insert into car (name, maker, year) values ('Explorer Sport Trac', 'Ford', 2007);
insert into car (name, maker, year) values ('57', 'Maybach', 2003);
insert into car (name, maker, year) values ('Tiburon', 'Hyundai', 2001);
insert into car (name, maker, year) values ('S60', 'Volvo', 2006);
insert into car (name, maker, year) values ('Land Cruiser', 'Toyota', 1997);
insert into car (name, maker, year) values ('Suburban 1500', 'GMC', 1994);
insert into car (name, maker, year) values ('Mazdaspeed 3', 'Mazda', 2009);
insert into car (name, maker, year) values ('Z3', 'BMW', 1996);
insert into car (name, maker, year) values ('Savana 1500', 'GMC', 2012);
insert into car (name, maker, year) values ('Phantom', 'Rolls-Royce', 2006);
insert into car (name, maker, year) values ('Sierra 2500', 'GMC', 2000);
insert into car (name, maker, year) values ('Maxima', 'Nissan', 2006);
insert into car (name, maker, year) values ('Express 2500', 'Chevrolet', 2008);
insert into car (name, maker, year) values ('Grand Marquis', 'Mercury', 2000);
insert into car (name, maker, year) values ('Altima', 'Nissan', 2013);
insert into car (name, maker, year) values ('BRZ', 'Subaru', 2013);
insert into car (name, maker, year) values ('Roadster', 'Tesla', 2010);
insert into car (name, maker, year) values ('Range Rover', 'Land Rover', 1990);
insert into car (name, maker, year) values ('Suburban 1500', 'GMC', 1996);
insert into car (name, maker, year) values ('Rendezvous', 'Buick', 2006);
insert into car (name, maker, year) values ('Integra', 'Acura', 1995);
insert into car (name, maker, year) values ('F-Series', 'Ford', 1986);
insert into car (name, maker, year) values ('7 Series', 'BMW', 2008);
insert into car (name, maker, year) values ('S-Class', 'Mercedes-Benz', 1984);
insert into car (name, maker, year) values ('Equator', 'Suzuki', 2010);
insert into car (name, maker, year) values ('SC', 'Lexus', 2003);
insert into car (name, maker, year) values ('430', 'Maserati', 1990);
insert into car (name, maker, year) values ('Leone', 'Subaru', 1987);
insert into car (name, maker, year) values ('Courier', 'Ford', 1986);
insert into car (name, maker, year) values ('Durango', 'Dodge', 1998);
insert into car (name, maker, year) values ('Land Cruiser', 'Toyota', 2007);
insert into car (name, maker, year) values ('Tempo', 'Ford', 1991);
insert into car (name, maker, year) values ('Bonneville', 'Pontiac', 1998);
insert into car (name, maker, year) values ('Savana 1500', 'GMC', 2003);
insert into car (name, maker, year) values ('RX-7', 'Mazda', 1991);
insert into car (name, maker, year) values ('F-Series', 'Ford', 1991);
insert into car (name, maker, year) values ('Cirrus', 'Chrysler', 2000);
insert into car (name, maker, year) values ('Camry', 'Toyota', 1997);
insert into car (name, maker, year) values ('Commander', 'Jeep', 2008);
insert into car (name, maker, year) values ('Routan', 'Volkswagen', 2011);
insert into car (name, maker, year) values ('Firebird', 'Pontiac', 1967);
insert into car (name, maker, year) values ('Tempest', 'Pontiac', 1966);
insert into car (name, maker, year) values ('Lumina', 'Chevrolet', 1993);
insert into car (name, maker, year) values ('S40', 'Volvo', 2009);
insert into car (name, maker, year) values ('Jimmy', 'GMC', 1997);
insert into car (name, maker, year) values ('Tercel', 'Toyota', 1993);
insert into car (name, maker, year) values ('Savana 1500', 'GMC', 1998);
insert into car (name, maker, year) values ('Century', 'Buick', 2002);
insert into car (name, maker, year) values ('LR2', 'Land Rover', 2008);
insert into car (name, maker, year) values ('Topaz', 'Mercury', 1988);
insert into car (name, maker, year) values ('Thunderbird', 'Ford', 1996);
insert into car (name, maker, year) values ('Intrigue', 'Oldsmobile', 2002);
insert into car (name, maker, year) values ('Milan', 'Mercury', 2008);
insert into car (name, maker, year) values ('Avalanche 2500', 'Chevrolet', 2003);
insert into car (name, maker, year) values ('530', 'BMW', 2004);
insert into car (name, maker, year) values ('Dynasty', 'Dodge', 1992);
insert into car (name, maker, year) values ('Montero Sport', 'Mitsubishi', 1999);
insert into car (name, maker, year) values ('Yukon XL 2500', 'GMC', 2011);
insert into car (name, maker, year) values ('Range Rover Sport', 'Land Rover', 2011);
insert into car (name, maker, year) values ('Firebird', 'Pontiac', 1999);
insert into car (name, maker, year) values ('Tiburon', 'Hyundai', 1997);
insert into car (name, maker, year) values ('Camry Hybrid', 'Toyota', 2009);
insert into car (name, maker, year) values ('LaCrosse', 'Buick', 2012);
insert into car (name, maker, year) values ('Avalon', 'Toyota', 1996);
insert into car (name, maker, year) values ('PT Cruiser', 'Chrysler', 2008);
insert into car (name, maker, year) values ('9000', 'Saab', 1996);
insert into car (name, maker, year) values ('Chariot', 'Mitsubishi', 1994);
insert into car (name, maker, year) values ('4000s Quattro', 'Audi', 1986);
insert into car (name, maker, year) values ('Yukon XL 1500', 'GMC', 2006);
insert into car (name, maker, year) values ('SJ', 'Suzuki', 1987);
insert into car (name, maker, year) values ('Roadmaster', 'Buick', 1995);
insert into car (name, maker, year) values ('Trooper', 'Isuzu', 2000);
insert into car (name, maker, year) values ('Metro', 'Chevrolet', 2001);
insert into car (name, maker, year) values ('GT', 'Ford', 2005);
insert into car (name, maker, year) values ('Millenia', 'Mazda', 2000);
insert into car (name, maker, year) values ('Montana', 'Pontiac', 2003);
insert into car (name, maker, year) values ('1500', 'GMC', 1995);
insert into car (name, maker, year) values ('Grand Prix', 'Pontiac', 1991);
insert into car (name, maker, year) values ('Santa Fe', 'Hyundai', 2011);
insert into car (name, maker, year) values ('Jimmy', 'GMC', 1995);
insert into car (name, maker, year) values ('Expedition EL', 'Ford', 2007);
insert into car (name, maker, year) values ('Sierra 3500', 'GMC', 2002);
insert into car (name, maker, year) values ('Tempo', 'Ford', 1985);
insert into car (name, maker, year) values ('SL-Class', 'Mercedes-Benz', 1989);
insert into car (name, maker, year) values ('Grand Caravan', 'Dodge', 2003);
insert into car (name, maker, year) values ('i-280', 'Isuzu', 2006);
insert into car (name, maker, year) values ('Ram Van B350', 'Dodge', 1992);
insert into car (name, maker, year) values ('MR2', 'Toyota', 1986);
insert into car (name, maker, year) values ('Villager', 'Mercury', 2001);
insert into car (name, maker, year) values ('Cirrus', 'Chrysler', 2000);
insert into car (name, maker, year) values ('SC', 'Lexus', 1993);
insert into car (name, maker, year) values ('DBS', 'Aston Martin', 2010);
insert into car (name, maker, year) values ('Ion', 'Saturn', 2005);
insert into car (name, maker, year) values ('Previa', 'Toyota', 1994);
insert into car (name, maker, year) values ('Range Rover', 'Land Rover', 2009);
insert into car (name, maker, year) values ('Eurovan', 'Volkswagen', 1993);
insert into car (name, maker, year) values ('L300', 'Mitsubishi', 1987);
insert into car (name, maker, year) values ('Monte Carlo', 'Chevrolet', 2001);
insert into car (name, maker, year) values ('Lumina', 'Chevrolet', 1998);
insert into car (name, maker, year) values ('Starion', 'Mitsubishi', 1984);
insert into car (name, maker, year) values ('Silverado 1500', 'Chevrolet', 2001);
insert into car (name, maker, year) values ('Grand Vitara', 'Suzuki', 2009);
insert into car (name, maker, year) values ('Venza', 'Toyota', 2009);
insert into car (name, maker, year) values ('Bravada', 'Oldsmobile', 1992);
insert into car (name, maker, year) values ('Millenia', 'Mazda', 1999);
insert into car (name, maker, year) values ('Sienna', 'Toyota', 2001);
insert into car (name, maker, year) values ('Charger', 'Dodge', 1999);
insert into car (name, maker, year) values ('Durango', 'Dodge', 2001);
insert into car (name, maker, year) values ('Corolla', 'Toyota', 2009);
insert into car (name, maker, year) values ('Prius', 'Toyota', 2001);
