insert into product (name, brand, madein, price) values ('Eurovan', 'Volkswagen', 'Bulgaria', 46265.44);
insert into product (name, brand, madein, price) values ('Arnage', 'Bentley', 'China', 199813.81);
insert into product (name, brand, madein, price) values ('Frontier', 'Nissan', 'China', 175650.91);
insert into product (name, brand, madein, price) values ('Eurovan', 'Volkswagen', 'Portugal', 110704.43);
insert into product (name, brand, madein, price) values ('Vibe', 'Pontiac', 'China', 162021.33);
insert into product (name, brand, madein, price) values ('300C', 'Chrysler', 'Mongolia', 206790.61);
insert into product (name, brand, madein, price) values ('Navigator', 'Lincoln', 'Colombia', 108402.71);
insert into product (name, brand, madein, price) values ('Legacy', 'Subaru', 'Indonesia', 159726.49);
insert into product (name, brand, madein, price) values ('S6', 'Audi', 'Panama', 123984.66);
insert into product (name, brand, madein, price) values ('Tempest', 'Pontiac', 'Vietnam', 47313.0);
insert into product (name, brand, madein, price) values ('Impala', 'Chevrolet', 'United States', 214742.76);
insert into product (name, brand, madein, price) values ('Rodeo', 'Isuzu', 'Russia', 115527.06);
insert into product (name, brand, madein, price) values ('Yukon XL 2500', 'GMC', 'Liberia', 34819.38);
insert into product (name, brand, madein, price) values ('Impala', 'Chevrolet', 'Argentina', 54381.86);
insert into product (name, brand, madein, price) values ('Z4', 'BMW', 'Ukraine', 233716.15);
insert into product (name, brand, madein, price) values ('Charger', 'Dodge', 'Indonesia', 148441.61);
insert into product (name, brand, madein, price) values ('Grand Marquis', 'Mercury', 'Russia', 38459.46);
insert into product (name, brand, madein, price) values ('Grand Voyager', 'Plymouth', 'Argentina', 24020.98);
insert into product (name, brand, madein, price) values ('Silverado 3500', 'Chevrolet', 'Indonesia', 223453.97);
insert into product (name, brand, madein, price) values ('Sunfire', 'Pontiac', 'China', 185005.01);
insert into product (name, brand, madein, price) values ('GX', 'Lexus', 'South Korea', 64626.43);
insert into product (name, brand, madein, price) values ('3 Series', 'BMW', 'Poland', 21514.9);
insert into product (name, brand, madein, price) values ('Golf', 'Volkswagen', 'Serbia', 211812.43);
insert into product (name, brand, madein, price) values ('STS', 'Cadillac', 'Czech Republic', 204636.09);
insert into product (name, brand, madein, price) values ('GranSport', 'Maserati', 'United Arab Emirates', 81009.7);
insert into product (name, brand, madein, price) values ('Solara', 'Toyota', 'Indonesia', 183191.4);
insert into product (name, brand, madein, price) values ('5 Series', 'BMW', 'Tajikistan', 157513.01);
insert into product (name, brand, madein, price) values ('Sienna', 'Toyota', 'Indonesia', 48995.6);
insert into product (name, brand, madein, price) values ('LHS', 'Chrysler', 'Slovenia', 31344.37);
insert into product (name, brand, madein, price) values ('164', 'Alfa Romeo', 'China', 23733.45);
insert into product (name, brand, madein, price) values ('9000', 'Saab', 'Indonesia', 54720.17);
insert into product (name, brand, madein, price) values ('Century', 'Buick', 'Brazil', 46314.36);
insert into product (name, brand, madein, price) values ('Mustang', 'Ford', 'Sweden', 28261.47);
insert into product (name, brand, madein, price) values ('Sonata', 'Hyundai', 'China', 78280.24);
insert into product (name, brand, madein, price) values ('Cube', 'Nissan', 'China', 148502.69);
insert into product (name, brand, madein, price) values ('Silverado 3500', 'Chevrolet', 'Slovenia', 188493.49);
insert into product (name, brand, madein, price) values ('Savana 2500', 'GMC', 'China', 179434.03);
insert into product (name, brand, madein, price) values ('Yukon XL 2500', 'GMC', 'Greece', 153123.56);
insert into product (name, brand, madein, price) values ('Amigo', 'Isuzu', 'Indonesia', 41757.33);
insert into product (name, brand, madein, price) values ('911', 'Porsche', 'Indonesia', 76021.69);
insert into product (name, brand, madein, price) values ('Vandura 3500', 'GMC', 'Brazil', 27071.95);
insert into product (name, brand, madein, price) values ('Town & Country', 'Chrysler', 'China', 94932.24);
insert into product (name, brand, madein, price) values ('Tundra', 'Toyota', 'Indonesia', 233568.13);
insert into product (name, brand, madein, price) values ('Range Rover', 'Land Rover', 'Ukraine', 130536.69);
insert into product (name, brand, madein, price) values ('Tracker', 'Chevrolet', 'Ukraine', 190992.01);
insert into product (name, brand, madein, price) values ('Legacy', 'Subaru', 'China', 124761.11);
insert into product (name, brand, madein, price) values ('Civic', 'Honda', 'United States', 30328.58);
insert into product (name, brand, madein, price) values ('Corvette', 'Chevrolet', 'Indonesia', 76762.01);
insert into product (name, brand, madein, price) values ('Tribute', 'Mazda', 'China', 64657.87);
insert into product (name, brand, madein, price) values ('Camry Hybrid', 'Toyota', 'Israel', 71764.04);
insert into product (name, brand, madein, price) values ('Terraza', 'Buick', 'Sweden', 223279.27);
insert into product (name, brand, madein, price) values ('E350', 'Ford', 'France', 127623.41);
insert into product (name, brand, madein, price) values ('Silhouette', 'Oldsmobile', 'Poland', 178246.63);
insert into product (name, brand, madein, price) values ('IS F', 'Lexus', 'United Kingdom', 72513.78);
insert into product (name, brand, madein, price) values ('Express 2500', 'Chevrolet', 'France', 180600.77);
insert into product (name, brand, madein, price) values ('Eclipse', 'Mitsubishi', 'Finland', 59919.44);
insert into product (name, brand, madein, price) values ('Vibe', 'Pontiac', 'China', 165415.18);
insert into product (name, brand, madein, price) values ('Suburban', 'Chevrolet', 'United States', 169605.32);
insert into product (name, brand, madein, price) values ('Celica', 'Toyota', 'Nigeria', 126151.49);
insert into product (name, brand, madein, price) values ('Legend', 'Acura', 'China', 113499.07);
insert into product (name, brand, madein, price) values ('F350', 'Ford', 'Moldova', 203360.13);
insert into product (name, brand, madein, price) values ('S8', 'Audi', 'Greece', 223453.57);
insert into product (name, brand, madein, price) values ('GTI', 'Volkswagen', 'Uruguay', 55656.52);
insert into product (name, brand, madein, price) values ('GX', 'Lexus', 'Uruguay', 165503.84);
insert into product (name, brand, madein, price) values ('Tiguan', 'Volkswagen', 'Indonesia', 92512.42);
insert into product (name, brand, madein, price) values ('Type 2', 'Volkswagen', 'Ukraine', 100524.18);
insert into product (name, brand, madein, price) values ('Diablo', 'Lamborghini', 'Poland', 109678.99);
insert into product (name, brand, madein, price) values ('Tahoe', 'Chevrolet', 'Indonesia', 29510.56);
insert into product (name, brand, madein, price) values ('NV3500', 'Nissan', 'Liberia', 184506.27);
insert into product (name, brand, madein, price) values ('458 Italia', 'Ferrari', 'China', 247635.89);
insert into product (name, brand, madein, price) values ('Imperial', 'Chrysler', 'Sudan', 19817.69);
insert into product (name, brand, madein, price) values ('Samurai', 'Suzuki', 'Cuba', 101308.61);
insert into product (name, brand, madein, price) values ('T100', 'Toyota', 'China', 28346.05);
insert into product (name, brand, madein, price) values ('Ram Van 1500', 'Dodge', 'Andorra', 49176.3);
insert into product (name, brand, madein, price) values ('Silverado 2500', 'Chevrolet', 'Russia', 121012.35);
insert into product (name, brand, madein, price) values ('G-Series 3500', 'Chevrolet', 'China', 117424.96);
insert into product (name, brand, madein, price) values ('Elantra', 'Hyundai', 'Indonesia', 199993.96);
insert into product (name, brand, madein, price) values ('9-5', 'Saab', 'Dominican Republic', 147866.9);
insert into product (name, brand, madein, price) values ('Taurus', 'Ford', 'China', 17898.33);
insert into product (name, brand, madein, price) values ('Montero', 'Mitsubishi', 'China', 213537.44);
insert into product (name, brand, madein, price) values ('Mazda5', 'Mazda', 'Indonesia', 24826.1);
insert into product (name, brand, madein, price) values ('240SX', 'Nissan', 'Peru', 144718.81);
insert into product (name, brand, madein, price) values ('i-370', 'Isuzu', 'China', 180382.59);
insert into product (name, brand, madein, price) values ('4Runner', 'Toyota', 'China', 141404.16);
insert into product (name, brand, madein, price) values ('Genesis Coupe', 'Hyundai', 'Armenia', 124272.4);
insert into product (name, brand, madein, price) values ('tC', 'Scion', 'Finland', 234366.93);
insert into product (name, brand, madein, price) values ('929', 'Mazda', 'Indonesia', 87673.25);
insert into product (name, brand, madein, price) values ('Navigator', 'Lincoln', 'Poland', 197369.7);
insert into product (name, brand, madein, price) values ('200', 'Audi', 'Iran', 81147.83);
insert into product (name, brand, madein, price) values ('Touareg', 'Volkswagen', 'Indonesia', 158387.81);
insert into product (name, brand, madein, price) values ('G-Series G30', 'Chevrolet', 'Nigeria', 95120.71);
insert into product (name, brand, madein, price) values ('Bronco', 'Ford', 'Dominica', 175575.8);
insert into product (name, brand, madein, price) values ('X3', 'BMW', 'Indonesia', 241325.53);
insert into product (name, brand, madein, price) values ('Optima', 'Kia', 'China', 15642.81);
insert into product (name, brand, madein, price) values ('Aerostar', 'Ford', 'China', 169379.13);
insert into product (name, brand, madein, price) values ('Savana 1500', 'GMC', 'Brazil', 173810.28);
insert into product (name, brand, madein, price) values ('F-Series', 'Ford', 'Finland', 127758.9);
insert into product (name, brand, madein, price) values ('Corolla', 'Toyota', 'China', 165601.1);
insert into product (name, brand, madein, price) values ('TL', 'Acura', 'Philippines', 106679.17);
insert into product (name, brand, madein, price) values ('F-Series', 'Ford', 'Poland', 138401.42);
